spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/transactionmaster?currentSchema=tmsch
    username: postgres
    password: P@ssw0rd1
  flyway:
    enabled: true
    user: postgres
    password: P@ssw0rd1
    locations: classpath:db/migration/all, classpath:db/migration/dev
    schemas: tmsch